# Generated by Django 4.1.5 on 2023-01-28 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otakus', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
    ]
