# Generated by Django 4.1.5 on 2023-02-01 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otakus', '0002_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
