# Generated by Django 4.1.5 on 2023-02-02 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otakus', '0005_alter_contribution_reviewer_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contribution',
            name='reviewer_feedback',
        ),
        migrations.AddField(
            model_name='contribution',
            name='feedback',
            field=models.CharField(blank=True, choices=[('irr', 'not relevant'), ('dup', 'duplicate'), ('eas', 'too easy'), ('bad', 'bad choices'), ('inv', 'invalid/wrong information')], max_length=5, null=True),
        ),
    ]
