# Generated by Django 4.1.5 on 2023-04-01 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otakus', '0009_notification_broad_alter_notification_seen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='choice1',
            field=models.TextField(max_length=150),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice2',
            field=models.TextField(max_length=150),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice3',
            field=models.TextField(max_length=150),
        ),
        migrations.AlterField(
            model_name='question',
            name='right_answer',
            field=models.TextField(max_length=150),
        ),
    ]
