# Generated by Django 4.1.5 on 2023-04-28 11:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('otakus', '0010_alter_question_choice1_alter_question_choice2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='approved',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='contributor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='question',
            name='date_reviewed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='feedback',
            field=models.CharField(blank=True, choices=[('irr', 'not relevant'), ('dup', 'duplicate'), ('eas', 'too easy'), ('bad', 'bad choices'), ('inv', 'invalid/wrong information')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='is_contribution',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributions_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Contribution',
        ),
    ]
