# Generated by Django 4.1.5 on 2023-05-08 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import otakus.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('otakus', '0012_alter_question_contributor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='contributor',
            field=models.ForeignKey(default=otakus.helpers.get_superuser, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributions', to=settings.AUTH_USER_MODEL),
        ),
    ]
