# Generated by Django 4.1.5 on 2023-06-19 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otakus', '0013_alter_question_contributor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(blank=True, choices=[('NA', 'new available anime in quizes'), ('N', 'new anime to review'), ('R', 'review needed'), ('A', 'question approved'), ('A1', 'first question approved'), ('F', 'question rejected')], max_length=2, null=True),
        ),
    ]
