# Generated by Django 4.2.16 on 2024-10-30 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='ai_generated',
            field=models.BooleanField(default=False),
        ),
    ]
