export const get_domain = () => "127.0.0.1:8000"

//export const get_domain = () => "production domain:port"

export const DJANGO_URL = `http://${get_domain()}`

export const N_Game_Questions = 5

export const SelectStyles = {
    option: (provided) => ({
        ...provided,
        padding: 12,
    }),
    menuList: (base) => ({
        ...base,
        "::-webkit-scrollbar": {
            display: "none",
            width: "0px"
        }
    })
}

export const COUNTRIES = [
    { value: "ad", label: "Andorra" },
    { value: "ae", label: "United Arab Emirates" },
    { value: "af", label: "Afghanistan" },
    { value: "ag", label: "Antigua and Barbuda" },
    { value: "ai", label: "Anguilla" },
    { value: "al", label: "Albania" },
    { value: "am", label: "Armenia" },
    { value: "ao", label: "Angola" },
    { value: "aq", label: "Antarctica" },
    { value: "ar", label: "Argentina" },
    { value: "as", label: "American Samoa" },
    { value: "at", label: "Austria" },
    { value: "au", label: "Australia" },
    { value: "aw", label: "Aruba" },
    { value: "ax", label: "Åland Islands" },
    { value: "az", label: "Azerbaijan" },
    { value: "ba", label: "Bosnia and Herzegovina" },
    { value: "bb", label: "Barbados" },
    { value: "bd", label: "Bangladesh" },
    { value: "be", label: "Belgium" },
    { value: "bf", label: "Burkina Faso" },
    { value: "bg", label: "Bulgaria" },
    { value: "bh", label: "Bahrain" },
    { value: "bi", label: "Burundi" },
    { value: "bj", label: "Benin" },
    { value: "bl", label: "Saint Barthélemy" },
    { value: "bm", label: "Bermuda" },
    { value: "bn", label: "Brunei" },
    { value: "bo", label: "Bolivia" },
    { value: "bq", label: "Caribbean Netherlands" },
    { value: "br", label: "Brazil" },
    { value: "bs", label: "Bahamas" },
    { value: "bt", label: "Bhutan" },
    { value: "bv", label: "Bouvet Island" },
    { value: "bw", label: "Botswana" },
    { value: "by", label: "Belarus" },
    { value: "bz", label: "Belize" },
    { value: "ca", label: "Canada" },
    { value: "cc", label: "Cocos (Keeling) Islands" },
    { value: "cd", label: "DR Congo" },
    { value: "cf", label: "Central African Republic" },
    { value: "cg", label: "Republic of the Congo" },
    { value: "ch", label: "Switzerland" },
    { value: "ci", label: "Côte d'Ivoire (Ivory Coast)" },
    { value: "ck", label: "Cook Islands" },
    { value: "cl", label: "Chile" },
    { value: "cm", label: "Cameroon" },
    { value: "cn", label: "China" },
    { value: "co", label: "Colombia" },
    { value: "cr", label: "Costa Rica" },
    { value: "cu", label: "Cuba" },
    { value: "cv", label: "Cape Verde" },
    { value: "cw", label: "Curaçao" },
    { value: "cx", label: "Christmas Island" },
    { value: "cy", label: "Cyprus" },
    { value: "cz", label: "Czechia" },
    { value: "de", label: "Germany" },
    { value: "dj", label: "Djibouti" },
    { value: "dk", label: "Denmark" },
    { value: "dm", label: "Dominica" },
    { value: "do", label: "Dominican Republic" },
    { value: "dz", label: "Algeria" },
    { value: "ec", label: "Ecuador" },
    { value: "ee", label: "Estonia" },
    { value: "eg", label: "Egypt" },
    { value: "eh", label: "Western Sahara" },
    { value: "er", label: "Eritrea" },
    { value: "es", label: "Spain" },
    { value: "et", label: "Ethiopia" },
    { value: "eu", label: "European Union" },
    { value: "fi", label: "Finland" },
    { value: "fj", label: "Fiji" },
    { value: "fk", label: "Falkland Islands" },
    { value: "fm", label: "Micronesia" },
    { value: "fo", label: "Faroe Islands" },
    { value: "fr", label: "France" },
    { value: "ga", label: "Gabon" },
    { value: "gb", label: "United Kingdom" },
    { value: "gb-eng", label: "England" },
    { value: "gb-nir", label: "Northern Ireland" },
    { value: "gb-sct", label: "Scotland" },
    { value: "gb-wls", label: "Wales" },
    { value: "gd", label: "Grenada" },
    { value: "ge", label: "Georgia" },
    { value: "gf", label: "French Guiana" },
    { value: "gg", label: "Guernsey" },
    { value: "gh", label: "Ghana" },
    { value: "gi", label: "Gibraltar" },
    { value: "gl", label: "Greenland" },
    { value: "gm", label: "Gambia" },
    { value: "gn", label: "Guinea" },
    { value: "gp", label: "Guadeloupe" },
    { value: "gq", label: "Equatorial Guinea" },
    { value: "gr", label: "Greece" },
    { value: "gs", label: "South Georgia" },
    { value: "gt", label: "Guatemala" },
    { value: "gu", label: "Guam" },
    { value: "gw", label: "Guinea-Bissau" },
    { value: "gy", label: "Guyana" },
    { value: "hk", label: "Hong Kong" },
    { value: "hm", label: "Heard Island and McDonald Islands" },
    { value: "hn", label: "Honduras" },
    { value: "hr", label: "Croatia" },
    { value: "ht", label: "Haiti" },
    { value: "hu", label: "Hungary" },
    { value: "id", label: "Indonesia" },
    { value: "ie", label: "Ireland" },
    { value: "il", label: "Israel" },
    { value: "im", label: "Isle of Man" },
    { value: "in", label: "India" },
    { value: "io", label: "British Indian Ocean Territory" },
    { value: "iq", label: "Iraq" },
    { value: "ir", label: "Iran" },
    { value: "is", label: "Iceland" },
    { value: "it", label: "Italy" },
    { value: "je", label: "Jersey" },
    { value: "jm", label: "Jamaica" },
    { value: "jo", label: "Jordan" },
    { value: "jp", label: "Japan" },
    { value: "ke", label: "Kenya" },
    { value: "kg", label: "Kyrgyzstan" },
    { value: "kh", label: "Cambodia" },
    { value: "ki", label: "Kiribati" },
    { value: "km", label: "Comoros" },
    { value: "kn", label: "Saint Kitts and Nevis" },
    { value: "kp", label: "North Korea" },
    { value: "kr", label: "South Korea" },
    { value: "kw", label: "Kuwait" },
    { value: "ky", label: "Cayman Islands" },
    { value: "kz", label: "Kazakhstan" },
    { value: "la", label: "Laos" },
    { value: "lb", label: "Lebanon" },
    { value: "lc", label: "Saint Lucia" },
    { value: "li", label: "Liechtenstein" },
    { value: "lk", label: "Sri Lanka" },
    { value: "lr", label: "Liberia" },
    { value: "ls", label: "Lesotho" },
    { value: "lt", label: "Lithuania" },
    { value: "lu", label: "Luxembourg" },
    { value: "lv", label: "Latvia" },
    { value: "ly", label: "Libya" },
    { value: "ma", label: "Morocco" },
    { value: "mc", label: "Monaco" },
    { value: "md", label: "Moldova" },
    { value: "me", label: "Montenegro" },
    { value: "mf", label: "Saint Martin" },
    { value: "mg", label: "Madagascar" },
    { value: "mh", label: "Marshall Islands" },
    { value: "mk", label: "North Macedonia" },
    { value: "ml", label: "Mali" },
    { value: "mm", label: "Myanmar" },
    { value: "mn", label: "Mongolia" },
    { value: "mo", label: "Macau" },
    { value: "mp", label: "Northern Mariana Islands" },
    { value: "mq", label: "Martinique" },
    { value: "mr", label: "Mauritania" },
    { value: "ms", label: "Montserrat" },
    { value: "mt", label: "Malta" },
    { value: "mu", label: "Mauritius" },
    { value: "mv", label: "Maldives" },
    { value: "mw", label: "Malawi" },
    { value: "mx", label: "Mexico" },
    { value: "my", label: "Malaysia" },
    { value: "mz", label: "Mozambique" },
    { value: "na", label: "Namibia" },
    { value: "nc", label: "New Caledonia" },
    { value: "ne", label: "Niger" },
    { value: "nf", label: "Norfolk Island" },
    { value: "ng", label: "Nigeria" },
    { value: "ni", label: "Nicaragua" },
    { value: "nl", label: "Netherlands" },
    { value: "no", label: "Norway" },
    { value: "np", label: "Nepal" },
    { value: "nr", label: "Nauru" },
    { value: "nu", label: "Niue" },
    { value: "nz", label: "New Zealand" },
    { value: "om", label: "Oman" },
    { value: "pa", label: "Panama" },
    { value: "pe", label: "Peru" },
    { value: "pf", label: "French Polynesia" },
    { value: "pg", label: "Papua New Guinea" },
    { value: "ph", label: "Philippines" },
    { value: "pk", label: "Pakistan" },
    { value: "pl", label: "Poland" },
    { value: "pm", label: "Saint Pierre and Miquelon" },
    { value: "pn", label: "Pitcairn Islands" },
    { value: "pr", label: "Puerto Rico" },
    { value: "ps", label: "Palestine" },
    { value: "pt", label: "Portugal" },
    { value: "pw", label: "Palau" },
    { value: "py", label: "Paraguay" },
    { value: "qa", label: "Qatar" },
    { value: "re", label: "Réunion" },
    { value: "ro", label: "Romania" },
    { value: "rs", label: "Serbia" },
    { value: "ru", label: "Russia" },
    { value: "rw", label: "Rwanda" },
    { value: "sa", label: "Saudi Arabia" },
    { value: "sb", label: "Solomon Islands" },
    { value: "sc", label: "Seychelles" },
    { value: "sd", label: "Sudan" },
    { value: "se", label: "Sweden" },
    { value: "sg", label: "Singapore" },
    { value: "sh", label: "Saint Helena, Ascension and Tristan da Cunha" },
    { value: "si", label: "Slovenia" },
    { value: "sj", label: "Svalbard and Jan Mayen" },
    { value: "sk", label: "Slovakia" },
    { value: "sl", label: "Sierra Leone" },
    { value: "sm", label: "San Marino" },
    { value: "sn", label: "Senegal" },
    { value: "so", label: "Somalia" },
    { value: "sr", label: "Suriname" },
    { value: "ss", label: "South Sudan" },
    { value: "st", label: "São Tomé and Príncipe" },
    { value: "sv", label: "El Salvador" },
    { value: "sx", label: "Sint Maarten" },
    { value: "sy", label: "Syria" },
    { value: "sz", label: "Eswatini (Swaziland)" },
    { value: "tc", label: "Turks and Caicos Islands" },
    { value: "td", label: "Chad" },
    { value: "tf", label: "French Southern and Antarctic Lands" },
    { value: "tg", label: "Togo" },
    { value: "th", label: "Thailand" },
    { value: "tj", label: "Tajikistan" },
    { value: "tk", label: "Tokelau" },
    { value: "tl", label: "Timor-Leste" },
    { value: "tm", label: "Turkmenistan" },
    { value: "tn", label: "Tunisia" },
    { value: "to", label: "Tonga" },
    { value: "tr", label: "Turkey" },
    { value: "tt", label: "Trinidad and Tobago" },
    { value: "tv", label: "Tuvalu" },
    { value: "tw", label: "Taiwan" },
    { value: "tz", label: "Tanzania" },
    { value: "ua", label: "Ukraine" },
    { value: "ug", label: "Uganda" },
    { value: "um", label: "United States Minor Outlying Islands" },
    { value: "un", label: "United Nations" },
    { value: "us", label: "United States" },
    { value: "uy", label: "Uruguay" },
    { value: "uz", label: "Uzbekistan" },
    { value: "va", label: "Vatican City (Holy See)" },
    { value: "vc", label: "Saint Vincent and the Grenadines" },
    { value: "ve", label: "Venezuela" },
    { value: "vg", label: "British Virgin Islands" },
    { value: "vi", label: "United States Virgin Islands" },
    { value: "vn", label: "Vietnam" },
    { value: "vu", label: "Vanuatu" },
    { value: "wf", label: "Wallis and Futuna" },
    { value: "ws", label: "Samoa" },
    { value: "xk", label: "Kosovo" },
    { value: "ye", label: "Yemen" },
    { value: "yt", label: "Mayotte" },
    { value: "za", label: "South Africa" },
    { value: "zm", label: "Zambia" },
    { value: "zw", label: "Zimbabwe" }
]

export const COUNTRIES_DICT = {
    "ad": "Andorra",
    "ae": "United Arab Emirates",
    "af": "Afghanistan",
    "ag": "Antigua and Barbuda",
    "ai": "Anguilla",
    "al": "Albania",
    "am": "Armenia",
    "ao": "Angola",
    "aq": "Antarctica",
    "ar": "Argentina",
    "as": "American Samoa",
    "at": "Austria",
    "au": "Australia",
    "aw": "Aruba",
    "ax": "Åland Islands",
    "az": "Azerbaijan",
    "ba": "Bosnia and Herzegovina",
    "bb": "Barbados",
    "bd": "Bangladesh",
    "be": "Belgium",
    "bf": "Burkina Faso",
    "bg": "Bulgaria",
    "bh": "Bahrain",
    "bi": "Burundi",
    "bj": "Benin",
    "bl": "Saint Barthélemy",
    "bm": "Bermuda",
    "bn": "Brunei",
    "bo": "Bolivia",
    "bq": "Caribbean Netherlands",
    "br": "Brazil",
    "bs": "Bahamas",
    "bt": "Bhutan",
    "bv": "Bouvet Island",
    "bw": "Botswana",
    "by": "Belarus",
    "bz": "Belize",
    "ca": "Canada",
    "cc": "Cocos (Keeling) Islands",
    "cd": "DR Congo",
    "cf": "Central African Republic",
    "cg": "Republic of the Congo",
    "ch": "Switzerland",
    "ci": "Côte d'Ivoire (Ivory Coast)",
    "ck": "Cook Islands",
    "cl": "Chile",
    "cm": "Cameroon",
    "cn": "China",
    "co": "Colombia",
    "cr": "Costa Rica",
    "cu": "Cuba",
    "cv": "Cape Verde",
    "cw": "Curaçao",
    "cx": "Christmas Island",
    "cy": "Cyprus",
    "cz": "Czechia",
    "de": "Germany",
    "dj": "Djibouti",
    "dk": "Denmark",
    "dm": "Dominica",
    "do": "Dominican Republic",
    "dz": "Algeria",
    "ec": "Ecuador",
    "ee": "Estonia",
    "eg": "Egypt",
    "eh": "Western Sahara",
    "er": "Eritrea",
    "es": "Spain",
    "et": "Ethiopia",
    "eu": "European Union",
    "fi": "Finland",
    "fj": "Fiji",
    "fk": "Falkland Islands",
    "fm": "Micronesia",
    "fo": "Faroe Islands",
    "fr": "France",
    "ga": "Gabon",
    "gb": "United Kingdom",
    "gb-eng": "England",
    "gb-nir": "Northern Ireland",
    "gb-sct": "Scotland",
    "gb-wls": "Wales",
    "gd": "Grenada",
    "ge": "Georgia",
    "gf": "French Guiana",
    "gg": "Guernsey",
    "gh": "Ghana",
    "gi": "Gibraltar",
    "gl": "Greenland",
    "gm": "Gambia",
    "gn": "Guinea",
    "gp": "Guadeloupe",
    "gq": "Equatorial Guinea",
    "gr": "Greece",
    "gs": "South Georgia",
    "gt": "Guatemala",
    "gu": "Guam",
    "gw": "Guinea-Bissau",
    "gy": "Guyana",
    "hk": "Hong Kong",
    "hm": "Heard Island and McDonald Islands",
    "hn": "Honduras",
    "hr": "Croatia",
    "ht": "Haiti",
    "hu": "Hungary",
    "id": "Indonesia",
    "ie": "Ireland",
    "il": "Israel",
    "im": "Isle of Man",
    "in": "India",
    "io": "British Indian Ocean Territory",
    "iq": "Iraq",
    "ir": "Iran",
    "is": "Iceland",
    "it": "Italy",
    "je": "Jersey",
    "jm": "Jamaica",
    "jo": "Jordan",
    "jp": "Japan",
    "ke": "Kenya",
    "kg": "Kyrgyzstan",
    "kh": "Cambodia",
    "ki": "Kiribati",
    "km": "Comoros",
    "kn": "Saint Kitts and Nevis",
    "kp": "North Korea",
    "kr": "South Korea",
    "kw": "Kuwait",
    "ky": "Cayman Islands",
    "kz": "Kazakhstan",
    "la": "Laos",
    "lb": "Lebanon",
    "lc": "Saint Lucia",
    "li": "Liechtenstein",
    "lk": "Sri Lanka",
    "lr": "Liberia",
    "ls": "Lesotho",
    "lt": "Lithuania",
    "lu": "Luxembourg",
    "lv": "Latvia",
    "ly": "Libya",
    "ma": "Morocco",
    "mc": "Monaco",
    "md": "Moldova",
    "me": "Montenegro",
    "mf": "Saint Martin",
    "mg": "Madagascar",
    "mh": "Marshall Islands",
    "mk": "North Macedonia",
    "ml": "Mali",
    "mm": "Myanmar",
    "mn": "Mongolia",
    "mo": "Macau",
    "mp": "Northern Mariana Islands",
    "mq": "Martinique",
    "mr": "Mauritania",
    "ms": "Montserrat",
    "mt": "Malta",
    "mu": "Mauritius",
    "mv": "Maldives",
    "mw": "Malawi",
    "mx": "Mexico",
    "my": "Malaysia",
    "mz": "Mozambique",
    "na": "Namibia",
    "nc": "New Caledonia",
    "ne": "Niger",
    "nf": "Norfolk Island",
    "ng": "Nigeria",
    "ni": "Nicaragua",
    "nl": "Netherlands",
    "no": "Norway",
    "np": "Nepal",
    "nr": "Nauru",
    "nu": "Niue",
    "nz": "New Zealand",
    "om": "Oman",
    "pa": "Panama",
    "pe": "Peru",
    "pf": "French Polynesia",
    "pg": "Papua New Guinea",
    "ph": "Philippines",
    "pk": "Pakistan",
    "pl": "Poland",
    "pm": "Saint Pierre and Miquelon",
    "pn": "Pitcairn Islands",
    "pr": "Puerto Rico",
    "ps": "Palestine",
    "pt": "Portugal",
    "pw": "Palau",
    "py": "Paraguay",
    "qa": "Qatar",
    "re": "Réunion",
    "ro": "Romania",
    "rs": "Serbia",
    "ru": "Russia",
    "rw": "Rwanda",
    "sa": "Saudi Arabia",
    "sb": "Solomon Islands",
    "sc": "Seychelles",
    "sd": "Sudan",
    "se": "Sweden",
    "sg": "Singapore",
    "sh": "Saint Helena, Ascension and Tristan da Cunha",
    "si": "Slovenia",
    "sj": "Svalbard and Jan Mayen",
    "sk": "Slovakia",
    "sl": "Sierra Leone",
    "sm": "San Marino",
    "sn": "Senegal",
    "so": "Somalia",
    "sr": "Suriname",
    "ss": "South Sudan",
    "st": "São Tomé and Príncipe",
    "sv": "El Salvador",
    "sx": "Sint Maarten",
    "sy": "Syria",
    "sz": "Eswatini (Swaziland)",
    "tc": "Turks and Caicos Islands",
    "td": "Chad",
    "tf": "French Southern and Antarctic Lands",
    "tg": "Togo",
    "th": "Thailand",
    "tj": "Tajikistan",
    "tk": "Tokelau",
    "tl": "Timor-Leste",
    "tm": "Turkmenistan",
    "tn": "Tunisia",
    "to": "Tonga",
    "tr": "Turkey",
    "tt": "Trinidad and Tobago",
    "tv": "Tuvalu",
    "tw": "Taiwan",
    "tz": "Tanzania",
    "ua": "Ukraine",
    "ug": "Uganda",
    "um": "United States Minor Outlying Islands",
    "un": "United Nations",
    "us": "United States",
    "uy": "Uruguay",
    "uz": "Uzbekistan",
    "va": "Vatican City (Holy See)",
    "vc": "Saint Vincent and the Grenadines",
    "ve": "Venezuela",
    "vg": "British Virgin Islands",
    "vi": "United States Virgin Islands",
    "vn": "Vietnam",
    "vu": "Vanuatu",
    "wf": "Wallis and Futuna",
    "ws": "Samoa",
    "xk": "Kosovo",
    "ye": "Yemen",
    "yt": "Mayotte",
    "za": "South Africa",
    "zm": "Zambia",
    "zw": "Zimbabwe"
}
