# Generated by Django 4.2.4 on 2023-10-13 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='feedback',
            field=models.CharField(blank=True, choices=[('irr', 'not relevant'), ('eas', 'too easy'), ('bad', 'bad choices'), ('inv', 'invalid/wrong information')], max_length=5, null=True),
        ),
    ]
