# Generated by Django 3.1.4 on 2021-09-21 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_delete_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1)),
            ],
        ),
    ]
