# Generated by Django 3.1.4 on 2021-09-21 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
