# Generated by Django 3.1.4 on 2021-09-27 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_auto_20210927_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='TestsCount',
            field=models.IntegerField(default=0),
        ),
    ]
