# Generated by Django 3.1.4 on 2021-09-27 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_user_testscount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='score',
            new_name='points',
        ),
    ]
