# Generated by Django 3.1.4 on 2021-09-28 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0009_auto_20210927_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='highest_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
