# Generated by Django 3.1.4 on 2021-09-30 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0012_auto_20210928_0303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='TestsCount',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='highest_score',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.CharField(default='beginner', editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='points',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
