# Generated by Django 3.1.4 on 2021-09-30 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0013_auto_20210930_0522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='TestsCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='highest_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.CharField(default='beginner', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
