# Generated by Django 3.1.4 on 2021-10-02 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0014_auto_20210930_0524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='anime_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.CharField(default='beginner', max_length=30),
        ),
    ]
