# Generated by Django 3.1.4 on 2021-10-16 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0016_animescore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='highest_score',
        ),
    ]
