# Generated by Django 3.1.4 on 2021-10-20 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0017_remove_user_highest_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='animescore',
            name='TestsCount',
            field=models.IntegerField(default=0),
        ),
    ]
