# Generated by Django 3.1.4 on 2021-10-30 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0018_animescore_testscount'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
