# Generated by Django 3.1.4 on 2021-10-31 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0019_user_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='api_id',
            field=models.IntegerField(null=True),
        ),
    ]
