# Generated by Django 3.1.4 on 2021-10-31 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0020_anime_api_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='api_id',
        ),
        migrations.AddField(
            model_name='anime',
            name='url',
            field=models.CharField(default='/', max_length=300),
        ),
    ]
