# Generated by Django 3.1.4 on 2021-11-14 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0022_anime_total_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='choice4',
            field=models.TextField(null=True),
        ),
    ]
