# Generated by Django 3.1.4 on 2021-11-14 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0023_question_choice4'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='choice4',
        ),
    ]
