# Generated by Django 3.1.4 on 2021-11-14 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0025_question_choice4'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnimeScore',
        ),
    ]
