# Generated by Django 3.1.4 on 2021-11-19 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0026_delete_animescore'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='TestsCount',
            new_name='tests_completed',
        ),
    ]
