# Generated by Django 3.1.4 on 2021-11-19 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0027_auto_20211119_0612'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tests_started',
            field=models.IntegerField(default=0),
        ),
    ]
