# Generated by Django 3.1.4 on 2021-11-19 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0028_user_tests_started'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='best_score',
            field=models.IntegerField(default=0),
        ),
    ]
