# Generated by Django 3.1.4 on 2022-02-26 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0034_question_contributer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='contributer',
            new_name='contributor',
        ),
    ]
