# Generated by Django 3.1.4 on 2022-02-26 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0035_auto_20220226_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='approved',
            field=models.BooleanField(default=True),
        ),
    ]
