# Generated by Django 3.1.4 on 2022-02-28 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0036_question_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contributor',
            field=models.BooleanField(default=False),
        ),
    ]
