# Generated by Django 3.1.4 on 2022-02-28 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0037_user_contributor'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correct_answers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='wrong_answers',
            field=models.IntegerField(default=0),
        ),
    ]
