# Generated by Django 3.1.4 on 2022-02-28 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0038_auto_20220228_2125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='total_answers',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='total_score',
        ),
    ]
