# Generated by Django 3.1.4 on 2022-03-01 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0040_game_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='contributor',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributions', to=settings.AUTH_USER_MODEL),
        ),
    ]
