# Generated by Django 3.1.4 on 2022-03-01 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0043_question_statue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='statue',
            field=models.CharField(choices=[('1', 'approved'), ('-1', 'declined'), ('0', 'pending')], default='approved', max_length=20),
        ),
    ]
