# Generated by Django 3.1.4 on 2022-03-01 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0045_auto_20220301_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='approved',
        ),
    ]
