# Generated by Django 3.1.4 on 2022-03-02 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0047_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='status',
        ),
        migrations.AddField(
            model_name='question',
            name='approved',
            field=models.BooleanField(default=True),
        ),
    ]
