# Generated by Django 3.1.4 on 2022-03-02 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0048_auto_20220302_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='anime_name',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.CharField(choices=[('beginner', 'beginner'), ('intermediate', 'intermediate'), ('advanced', 'advanced'), ('realOtaku', 'realOtaku')], default='beginner', max_length=20),
        ),
    ]
