# Generated by Django 3.1.4 on 2022-03-03 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0049_auto_20220302_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contributions_count',
            field=models.IntegerField(default=0),
        ),
    ]
