# Generated by Django 3.1.4 on 2022-03-03 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0050_user_contributions_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
    ]
