# Generated by Django 3.1.4 on 2022-03-03 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0052_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='best_score',
        ),
        migrations.AddField(
            model_name='game',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
