# Generated by Django 3.1.4 on 2022-03-13 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0054_anime_questions_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='questions_number',
        ),
    ]
