# Generated by Django 3.1.4 on 2022-03-18 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0055_remove_anime_questions_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-points']},
        ),
        migrations.AddField(
            model_name='notification',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
