# Generated by Django 3.1.4 on 2022-04-15 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0056_auto_20220415_0901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='anime_review',
        ),
        migrations.AddField(
            model_name='user',
            name='anime_review',
            field=models.ManyToManyField(to='board.Anime'),
        ),
    ]
