# Generated by Django 3.1.4 on 2022-04-15 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0057_auto_20220415_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='anime_review',
            field=models.ManyToManyField(related_name='reviewer', to='board.Anime'),
        ),
    ]
