# Generated by Django 3.1.4 on 2022-04-15 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0058_auto_20220415_1002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='anime_review',
        ),
        migrations.AddField(
            model_name='user',
            name='animes_to_review',
            field=models.ManyToManyField(related_name='reviewers', to='board.Anime'),
        ),
    ]
