# Generated by Django 3.1.4 on 2022-04-24 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0059_auto_20220415_1003'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anime',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.CharField(choices=[('beginner', 'beginner'), ('intermediate', 'intermediate'), ('advanced', 'advanced'), ('realOtaku', 'realOtaku')], default='beginner', max_length=12),
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
