# Generated by Django 3.1.4 on 2022-04-24 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0060_auto_20220424_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='animes_to_review',
            field=models.ManyToManyField(blank=True, related_name='reviewers', to='board.Anime'),
        ),
    ]
