# Generated by Django 3.1.4 on 2022-04-24 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0061_auto_20220424_0305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='time',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
