# Generated by Django 3.1.4 on 2022-04-25 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0062_auto_20220424_0629'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='contributions',
            field=models.IntegerField(default=0),
        ),
    ]
