# Generated by Django 3.1.4 on 2022-04-25 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0064_auto_20220425_0427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='anime',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anime_questions', to='board.anime'),
        ),
    ]
