# Generated by Django 3.1.4 on 2022-05-31 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0065_auto_20220425_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(max_length=300, unique=True),
        ),
    ]
