# Generated by Django 3.1.4 on 2022-05-31 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0066_auto_20220531_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='choice1',
            field=models.TextField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice2',
            field=models.TextField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice3',
            field=models.TextField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice4',
            field=models.TextField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='right_answer',
            field=models.TextField(max_length=150, null=True),
        ),
    ]
