# Generated by Django 3.1.4 on 2022-06-07 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0067_auto_20220531_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='animes_for_quiz',
            field=models.ManyToManyField(blank=True, related_name='quiz_takers', to='board.Anime'),
        ),
    ]
