# Generated by Django 3.1.4 on 2022-06-08 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0068_user_animes_for_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='anime',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anime_questions', to='board.anime'),
        ),
    ]
