# Generated by Django 3.1.4 on 2022-06-10 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0069_auto_20220608_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='animes_for_quiz',
        ),
    ]
