# Generated by Django 3.1.4 on 2022-06-20 06:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0071_auto_20220614_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='contributor',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributions', to=settings.AUTH_USER_MODEL),
        ),
    ]
