# Generated by Django 3.1.4 on 2022-07-10 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0075_auto_20220709_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='choice1',
            field=models.TextField(max_length=150),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice2',
            field=models.TextField(max_length=150),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice3',
            field=models.TextField(max_length=150),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice4',
            field=models.TextField(max_length=150),
        ),
        migrations.AlterField(
            model_name='question',
            name='right_answer',
            field=models.TextField(max_length=150),
        ),
    ]
