# Generated by Django 3.1.4 on 2022-07-10 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0076_auto_20220710_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='anime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anime_questions', to='board.anime'),
        ),
    ]
