# Generated by Django 3.1.4 on 2022-07-17 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0078_auto_20220710_2231'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-id']},
        ),
    ]
