# Generated by Django 3.1.4 on 2022-07-19 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0079_auto_20220717_0045'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['-id']},
        ),
    ]
