# Generated by Django 3.1.4 on 2022-07-19 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0081_auto_20220719_0242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='url',
            field=models.CharField(blank=True, default='/', max_length=300),
        ),
    ]
