# Generated by Django 3.1.4 on 2022-07-26 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0083_auto_20220722_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(max_length=300),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(fields=('anime', 'question'), name='unique question for each anime'),
        ),
    ]
