# Generated by Django 3.1.4 on 2022-07-27 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0085_auto_20220726_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='anime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='anime_questions', to='board.anime'),
        ),
    ]
