# Generated by Django 3.1.4 on 2022-07-28 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0086_protect_question_on_anime_deletion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='choice1',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice2',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice3',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice4',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='question',
            name='right_answer',
            field=models.CharField(max_length=150),
        ),
    ]
