# Generated by Django 3.1.4 on 2022-08-04 10:31

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0087_charfield_on_choices'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anime',
            options={},
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
