# Generated by Django 3.1.4 on 2022-08-14 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0087_charfield_on_choices'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anime',
            options={},
        ),
        migrations.RemoveField(
            model_name='question',
            name='choice4',
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
