# Generated by Django 3.1.4 on 2022-08-17 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0088_auto_20220814_0217'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='reviewer_feedback',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
