# Generated by Django 3.1.4 on 2022-08-05 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0088_auto_20220804_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
