# Generated by Django 3.1.4 on 2022-08-05 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0089_auto_20220805_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='choice4',
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
