# Generated by Django 3.1.4 on 2022-08-26 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0092_auto_20220826_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='change_required',
        ),
    ]
