# Generated by Django 3.1.4 on 2022-08-28 19:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0095_auto_20220826_1811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='contributions',
        ),
        migrations.RemoveField(
            model_name='question',
            name='contributor',
        ),
        migrations.RemoveField(
            model_name='user',
            name='contributions_count',
        ),
        migrations.RemoveField(
            model_name='user',
            name='contributor',
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('approved', 'approved'), ('pending', 'pending'), ('rejected', 'rejected')], default='pending', max_length=20)),
                ('date_activated', models.DateTimeField(blank=True, null=True)),
                ('contributor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributions', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contribution', to='board.question')),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
