# Generated by Django 3.1.4 on 2022-08-28 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0096_auto_20220828_1915'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contribution',
            options={'ordering': ['-id']},
        ),
    ]
