# Generated by Django 3.1.4 on 2022-08-28 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0097_auto_20220828_1919'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contribution',
            old_name='date_activated',
            new_name='date_approved',
        ),
    ]
