# Generated by Django 3.1.4 on 2022-08-28 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0098_auto_20220828_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contribution', to='board.question', unique=True),
        ),
    ]
