# Generated by Django 3.1.4 on 2022-08-31 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0101_remove_contribution_reviewer'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='production',
            field=models.BooleanField(default=False),
        ),
    ]
