# Generated by Django 3.1.4 on 2022-09-01 20:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0102_question_production'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contribution',
            options={},
        ),
        migrations.AddField(
            model_name='contribution',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributions_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contribution',
            name='reviewer_feedback',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
