# Generated by Django 3.1.4 on 2022-09-02 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0103_auto_20220901_2048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='production',
            new_name='active',
        ),
        migrations.RemoveField(
            model_name='contribution',
            name='state',
        ),
    ]
