# Generated by Django 3.1.4 on 2022-09-02 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0104_auto_20220902_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contribution',
            name='date_approved',
        ),
        migrations.AddField(
            model_name='question',
            name='date_approved',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
