# Generated by Django 3.1.4 on 2022-09-02 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0105_auto_20220902_2137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='date_approved',
        ),
        migrations.AddField(
            model_name='contribution',
            name='date_reviewed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
