# Generated by Django 3.1.4 on 2022-09-03 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0106_auto_20220902_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('R', 'question needs review'), ('A', 'question approved'), ('F', 'question rejected')], max_length=1, null=True),
        ),
    ]
