# Generated by Django 3.1.4 on 2022-09-03 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0108_auto_20220903_0157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contribution',
            old_name='reviewed_by',
            new_name='reviewer',
        ),
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(blank=True, choices=[('R', 'review needed'), ('A', 'question approved'), ('F', 'question rejected'), ('D', 'question deleted')], max_length=1, null=True),
        ),
    ]
