# Generated by Django 3.1.4 on 2022-09-05 02:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0109_auto_20220903_2104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='advanced',
        ),
        migrations.RemoveField(
            model_name='question',
            name='approved',
        ),
        migrations.AddField(
            model_name='contribution',
            name='approved',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='answered_right',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quizes_taken', to='board.question'),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_quizes', to=settings.AUTH_USER_MODEL),
        ),
    ]
