# Generated by Django 3.1.4 on 2022-09-19 05:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0110_auto_20220905_0215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='answered_right',
        ),
        migrations.RemoveField(
            model_name='game',
            name='game_owner',
        ),
        migrations.RemoveField(
            model_name='game',
            name='question',
        ),
        migrations.AddField(
            model_name='game',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_games', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='QuestionInteraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='board.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions_interacted_with', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
