# Generated by Django 3.1.4 on 2022-09-19 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0111_auto_20220919_0503'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Game',
        ),
    ]
