# Generated by Django 3.1.4 on 2022-09-20 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0112_delete_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
