# Generated by Django 3.1.4 on 2022-09-20 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0113_anime_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='questioninteraction',
            name='anime',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='anime_interactions', to='board.anime'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questioninteraction',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_interactions', to='board.question'),
        ),
    ]
