# Generated by Django 3.1.4 on 2022-09-22 04:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0114_auto_20220920_0807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questioninteraction',
            name='correct',
        ),
        migrations.AddField(
            model_name='questioninteraction',
            name='correct_answer',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='question',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contribution', to='board.question'),
        ),
        migrations.AlterField(
            model_name='questioninteraction',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions_interacted_with', to=settings.AUTH_USER_MODEL),
        ),
    ]
