# Generated by Django 3.1.4 on 2022-09-25 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0115_auto_20220922_0458'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='questioninteraction',
            constraint=models.UniqueConstraint(fields=('user', 'question'), name='user interacts with each question just once'),
        ),
    ]
