# Generated by Django 3.1.4 on 2022-10-01 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0116_auto_20220925_0853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='date_created',
        ),
    ]
