# Generated by Django 3.1.4 on 2022-10-01 12:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0117_remove_question_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
