# Generated by Django 3.1.4 on 2022-10-04 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0120_auto_20221004_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tests_completed',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tests_started',
        ),
    ]
