# Generated by Django 3.1.4 on 2022-10-04 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0121_auto_20221004_1404'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('games', models.PositiveSmallIntegerField(default=1)),
                ('completed', models.BooleanField(default=False)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='anime_games', to='board.anime')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_games', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
