# Generated by Django 3.1.4 on 2022-10-18 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0123_auto_20221008_0019'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Game',
        ),
    ]
