# Generated by Django 3.1.4 on 2022-10-22 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0126_auto_20221022_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.CharField(choices=[('1', 'beginner'), ('2', 'intermediate'), ('3', 'advanced'), ('4', 'realOtaku')], default='1', max_length=12),
        ),
    ]
