# Generated by Django 3.1.4 on 2022-11-27 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0129_auto_20221022_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='url',
        ),
        migrations.AlterField(
            model_name='contribution',
            name='reviewer_feedback',
            field=models.CharField(blank=True, choices=[('not clear', 'not clear'), ('similar choices', 'similar choices'), ('too easy', 'too easy'), ('wrong information', 'wrong information')], max_length=50, null=True),
        ),
    ]
