# Generated by Django 3.1.4 on 2023-01-15 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0130_auto_20221127_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='reviewer_feedback',
            field=models.CharField(blank=True, choices=[('irrelevant', 'not relevant'), ('easy', 'too easy'), ('bad_choices', 'bad choices'), ('invalid', 'invalid/wrong information')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(blank=True, choices=[('N', 'new anime to review'), ('R', 'review needed'), ('A', 'question approved'), ('F', 'question rejected')], max_length=1, null=True),
        ),
    ]
