# Generated by Django 3.1.4 on 2023-01-21 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0131_auto_20230115_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(blank=True, choices=[('NA', 'new available anime in quizes'), ('N', 'new anime to review'), ('R', 'review needed'), ('A', 'question approved'), ('F', 'question rejected')], max_length=2, null=True),
        ),
    ]
